lib: [
  "_build/install/default/lib/ocaml_sql/META"
  "_build/install/default/lib/ocaml_sql/dune-package"
  "_build/install/default/lib/ocaml_sql/ocaml_sql.a"
  "_build/install/default/lib/ocaml_sql/ocaml_sql.cma"
  "_build/install/default/lib/ocaml_sql/ocaml_sql.cmi"
  "_build/install/default/lib/ocaml_sql/ocaml_sql.cmt"
  "_build/install/default/lib/ocaml_sql/ocaml_sql.cmx"
  "_build/install/default/lib/ocaml_sql/ocaml_sql.cmxa"
  "_build/install/default/lib/ocaml_sql/ocaml_sql.ml"
  "_build/install/default/lib/ocaml_sql/ocaml_sql__Sql.cmi"
  "_build/install/default/lib/ocaml_sql/ocaml_sql__Sql.cmt"
  "_build/install/default/lib/ocaml_sql/ocaml_sql__Sql.cmx"
  "_build/install/default/lib/ocaml_sql/opam"
  "_build/install/default/lib/ocaml_sql/sql.ml"
]
libexec: [
  "_build/install/default/lib/ocaml_sql/ocaml_sql.cmxs"
]
bin: [
  "_build/install/default/bin/ocaml_sql"
]
